"use client";

import React, { useEffect, useRef, useState } from "react";
import { CheckCircle2, RotateCcw } from "lucide-react";

const leftMenu = [
  "e-Waybill",
  "Generate New",
  "Generate Bulk",
  "Update Part B/Vehicle",
  "Update Vehicle-Bulk",
  "Change to Multivehicle",
  "Extend Validity",
  "Update EWB Transporter",
  "Update EWB Trans. Bulk",
  "Cancel",
  "Print EWB",
  "Consolidated EWB",
  "Reject",
  "Reports",
  "My Masters",
  "User Management",
  "Registration",
  "Update",
  "Grievance",
  "2Factor Authentication",
];

const stats = [
  {
    title: "EWBs generated by me",
    value: "",
    tone: "bg-[#42a567]",
  },
  {
    title: "EWBs cancelled by me",
    value: "",
    tone: "bg-[#7470b8]",
  },
  {
    title: "EWBs rejected by me",
    value: "",
    tone: "bg-[#c7953c]",
  },
  {
    title: "EWBs Gen. by other party on my GSTIN",
    value: "",
    tone: "bg-[#bd5a4e]",
  },
  {
    title: "My EWBs rejected by other party",
    value: "",
    tone: "bg-[#2bb1e0]",
  },
  {
    title: "EWB pending for Part-B updation",
    value: "",
    tone: "bg-[#9ea8b6]",
  },
];

const updates = [
  {
    date: "28 JUL 2023",
    text: "Mandatory 2 Factor Authentication for taxpayers with AATO above 100 Cr is further extended till 20/08/2023.",
  },
  {
    date: "26 MAY 2023",
    text: "Latest updates on 2 Factor Authentication, Deregistration of Enrolment and Common Enrolment have been issued.",
  },
  {
    date: "07 OCT 2022",
    text: "Single sign-on (SSO) for e-Invoice and e-Waybill enabled.",
  },
  {
    date: "14 SEP 2022",
    text: "e-Waybill for Gold will be available only after the notification is issued by Government.",
  },
];

interface GSTEWayBillDashboardProps {
  onComplete?: () => void;
}

export default function GSTEWayBillDashboard({
  onComplete,
}: GSTEWayBillDashboardProps = {}) {
  const primaryMenu = leftMenu.slice(1, 11);
  const secondaryMenu = leftMenu.slice(11);
  const [showLaunchScreen, setShowLaunchScreen] = useState(true);
  const [isStartingExperiment, setIsStartingExperiment] = useState(false);
  const [showGenerateOverlay, setShowGenerateOverlay] = useState(false);
  const launchTimerRef = useRef<number | null>(null);

  useEffect(() => {
    return () => {
      if (launchTimerRef.current !== null) {
        window.clearTimeout(launchTimerRef.current);
      }
    };
  }, []);

  const handleStartExperiment = () => {
    if (isStartingExperiment) {
      return;
    }

    setIsStartingExperiment(true);
    launchTimerRef.current = window.setTimeout(() => {
      setShowLaunchScreen(false);
    }, 1500);
  };

  return (
    <div className="relative min-h-screen overflow-hidden bg-[#e7e0fb] text-slate-900">
      <aside className="fixed left-0 top-0 z-30 h-screen w-[240px] overflow-hidden border-r-[3px] border-red-500 bg-[#6f74b8] shadow-[0_2px_8px_rgba(15,23,42,0.12)]">
        <div className="bg-[#c4b07c] px-4 py-4 text-[14px] font-semibold text-slate-900">
          e-Waybill
        </div>
        <div className="border-x-2 border-b-2 border-red-500">
          <div className="divide-y divide-white/20">
            {primaryMenu.map((item, index) => (
              <button
                key={item}
                type="button"
                onClick={() => {
                  if (index === 0) {
                    setShowGenerateOverlay(true);
                    onComplete?.();
                  }
                }}
                className={`block w-full px-4 py-3 text-left text-[12px] font-medium text-white transition-colors hover:bg-[#243647] ${
                  index === 0 ? "border-b border-red-500 bg-[#2f4158]" : "bg-[#2f4158]"
                }`}
              >
                {item}
              </button>
            ))}
          </div>
        </div>
        <div className="divide-y divide-white/20">
          {secondaryMenu.map((item) => (
            <button
              key={item}
              type="button"
              className="block w-full bg-[#6f74b8] px-4 py-3 text-left text-[12px] font-medium text-white transition-colors hover:bg-white/10"
            >
              {item}
            </button>
          ))}
        </div>
      </aside>

      <main className="min-h-screen pl-[240px]">
        <div className="min-h-screen bg-[#e7e0fb] px-4 py-4">
          <div className="grid gap-2 xl:grid-cols-6">
            {stats.map((item) => (
              <div
                key={item.title}
                className={`min-h-[225px] ${item.tone} overflow-hidden text-white shadow-[0_1px_4px_rgba(15,23,42,0.12)]`}
              >
                <div className="border-b border-white/10 px-4 py-4 text-[14px] font-semibold leading-tight">
                  {item.title}
                </div>
                <div className="flex h-[calc(100%-64px)] items-center justify-center px-4 text-center">
                  <div className="text-[44px] font-black tracking-tight opacity-15">
                    {item.value}
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-5 flex justify-start">
            <article className="w-full overflow-hidden bg-white shadow-[0_2px_8px_rgba(15,23,42,0.08)] xl:w-1/2">
              <div className="flex items-center justify-between border-b border-slate-200 px-4 py-3">
                <div className="text-[28px] font-bold italic text-[#69afd6]">Latest Updates</div>
                <div className="text-[18px] font-medium text-slate-700">31/05/2023</div>
              </div>
              <div className="px-4 py-4 text-[13px] leading-6 text-slate-700">
                <ol className="space-y-2.5">
                  {updates.map((item, index) => (
                    <li key={`${item.date}-${index}`}>
                      <span className="font-bold">{index + 1}. </span>
                      <span className="font-bold">{item.date} </span>
                      <span>{item.text}</span>
                    </li>
                  ))}
                </ol>
                <div className="mt-4 flex justify-end">
                  <button
                    type="button"
                    className="rounded-sm bg-[#5a4bb0] px-4 py-2 text-[13px] font-semibold text-white"
                  >
                    Previous Updates
                  </button>
                </div>
              </div>
            </article>
          </div>
        </div>
      </main>

      {showGenerateOverlay && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 px-4 backdrop-blur-[2px]">
          <div className="flex flex-col items-center">
            <div className="flex h-40 w-40 items-center justify-center rounded-full bg-[#47c65a] shadow-[0_22px_60px_rgba(71,198,90,0.35)]">
              <CheckCircle2 className="text-white" size={108} strokeWidth={2.2} />
            </div>
            <button
              type="button"
              onClick={() => setShowGenerateOverlay(false)}
              className="mt-4 inline-flex items-center gap-2 rounded-md bg-[#e1141a] px-6 py-3 text-[16px] font-semibold text-white shadow-[0_8px_20px_rgba(225,20,26,0.28)] transition-colors hover:bg-[#c90f15]"
            >
              <RotateCcw size={14} />
              Retry
            </button>
          </div>
        </div>
      )}

      {showLaunchScreen && (
        <div className="fixed inset-0 z-[110] flex items-center justify-center overflow-hidden bg-[#07111f]/22 px-4 text-white backdrop-blur-[2px]">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(255,255,255,0.06),transparent_30%),radial-gradient(circle_at_top_right,rgba(56,189,248,0.08),transparent_26%),linear-gradient(135deg,rgba(7,17,31,0.18)_0%,rgba(11,27,51,0.14)_45%,rgba(8,17,31,0.18)_100%)]" />
          <div className="absolute left-1/2 top-1/2 h-72 w-72 -translate-x-1/2 -translate-y-1/2 rounded-full bg-sky-400/5 blur-3xl" />
          <div className="relative z-10 flex h-full w-full items-center justify-center">
            <button
              type="button"
              onClick={handleStartExperiment}
              disabled={isStartingExperiment}
              className="inline-flex min-h-[72px] w-[min(84vw,34rem)] items-center justify-center rounded-[22px] bg-[#1244b8] px-6 text-lg font-black uppercase tracking-[0.12em] text-white shadow-[0_18px_40px_rgba(18,68,184,0.24)] transition-transform duration-200 hover:scale-[1.02] hover:bg-[#0f3a9a] disabled:cursor-wait disabled:opacity-90 sm:min-h-[78px] sm:px-8 sm:text-xl"
              aria-label="Start Experiment"
              title="Start Experiment"
            >
              {isStartingExperiment ? "EXPERIMENTING..." : "START EXPERIMENT"}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
