"use client";

import React, { useState } from "react";
import { useRouter } from "next/navigation";
import {
  FaArrowLeft,
  FaBars,
  FaCog,
  FaCube,
  FaExclamationTriangle,
  FaFileInvoice,
  FaHome,
  FaInfoCircle,
  FaPlay,
  FaPowerOff,
  FaVideo,
} from "react-icons/fa";
import ExperimentLaunchScreen from "./ExperimentLaunchScreen";
import ClipboardOnlyGuard from "./ClipboardOnlyGuard";
import GSTSimulation from "./GSTSimulation";

type Screen = "home" | "dashboard" | "invoice";

const latestUpdates = [
  {
    date: "01 OCT 2023",
    color: "blue",
    text: "Implementation of atleast 6 digit HSN in e-Invoices and e-Waybills has been deferred.",
  },
  {
    date: "19 SEP 2023",
    color: "green",
    text: "The tax payers, notified for generation of e-invoices and supplying to government departments / agencies, need to generate B2B e-Invoices with the GSTIN of the Government department / agency.",
  },
  {
    date: "11 SEP 2023",
    color: "orange",
    text: "2-Factor Authentication for all taxpayers with AATO above Rs 20 Cr is mandatory from 1st November 2023.",
  },
  {
    date: "11 SEP 2023",
    color: "red",
    text: "As per directions by GST Authority, a time limit of 30 days for reporting of invoices from date of invoice is imposed on e-invoice portals, and is applicable for taxpayers with AATO greater than or equal to 100 crores from 1st November 2023.",
  },
  {
    date: "09 AUG 2023",
    color: "purple",
    text: "Sub users can access e-Invoices generated by the main user.",
  },
];

interface GSTEInvoiceReplicaProps {
  initialScreen?: Screen;
}

export default function GSTEInvoiceReplica({
  initialScreen = "home",
}: GSTEInvoiceReplicaProps) {
  const router = useRouter();
  const [screen, setScreen] = useState<Screen>(initialScreen);
  const [showLaunchScreen, setShowLaunchScreen] = useState(true);
  const [showLoginModal, setShowLoginModal] = useState(false);
  const [loginData, setLoginData] = useState({
    username: "AIR",
    password: "Fin@123",
    captcha: "",
  });

  const goToInvoiceBuilder = () => {
    router.push("/simulations/gst/e-invoicing-1/invoice");
  };

  if (showLaunchScreen) {
    return (
      <ExperimentLaunchScreen
        title="GST E-Invoice Simulation"
        subtitle="A hazy fullscreen start screen that launches the simulation with one button in the center."
        onStart={() => setShowLaunchScreen(false)}
        buttonLabel="START EXPERIMENT"
        accent="blue"
      />
    );
  }

  const renderHomeScreen = () => (
    <div className="min-h-screen bg-gradient-to-b from-[#eef8fd] via-[#f6fbfe] to-[#edf5fb]">
      <div className="max-w-[1840px] mx-auto px-4 pt-6 pb-4">
        <div className="flex items-center justify-between gap-4 mb-2">
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <span className="text-xl font-semibold text-slate-900">
                GST Invoice preparation
              </span>
              <div className="w-40 bg-slate-200 rounded-full h-4 overflow-hidden">
                <div className="bg-blue-600 h-4 w-[30%]" />
              </div>
              <span className="text-xs font-semibold text-slate-700">30%</span>
            </div>
            <select className="border border-slate-300 rounded-md bg-white px-4 py-2 text-sm text-slate-700">
              <option>Language</option>
            </select>
          </div>
          <div className="text-lg font-semibold text-slate-900">
            e-invoicing
          </div>
          <div className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 py-2 shadow-sm">
            <div className="flex h-8 w-8 items-center justify-center rounded-full bg-amber-400 text-white font-bold">
              1850
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-cyan-100 bg-[#e0f2fa] p-4 shadow-sm">
          <div className="rounded-xl border-l-4 border-cyan-700 bg-[#e0f2fa] px-4 py-3 text-slate-800">
            <div className="text-base leading-6">
              Go to Login under Menu and Use the following Credentials to login:
            </div>
            <div className="mt-2">User name: AIR</div>
            <div>Password: Fin@123</div>
          </div>

          <div className="mt-3 overflow-hidden rounded-2xl border border-white/80 bg-white/70 shadow-[0_20px_60px_rgba(15,23,42,0.12)]">
            <div className="relative bg-[#2a6890] px-6 py-6 text-white">
              <div className="absolute inset-0 bg-white/18" />
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <div className="flex h-12 w-12 items-center justify-center rounded-full bg-white/85 text-[#1f6793] font-bold text-lg">
                    🇮🇳
                  </div>
                  <div>
                    <div className="text-xs font-bold uppercase tracking-[0.2em] opacity-70">
                      Goods and Services Tax
                    </div>
                    <div className="text-2xl font-semibold opacity-90">
                      e - INVOICE SYSTEM
                    </div>
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-3xl font-bold opacity-90">
                    e-Invoice 1 Portal
                  </div>
                </div>
                <div className="flex items-center gap-6 text-right">
                  <div>
                    <div className="text-sm font-semibold opacity-75">
                      NATION TAX MARKET
                    </div>
                    <div className="text-xs opacity-60">GST</div>
                  </div>
                  <div>
                    <div className="text-sm font-semibold opacity-75">
                      एनआईसी NIC
                    </div>
                    <div className="text-xs opacity-60">
                      National Informatics Centre
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex flex-wrap items-stretch border-b border-slate-200 bg-white/85">
              {["Home", "Laws", "Help", "Search", "Contact Us", "Registration", "Statistics"].map(
                (tab, index) => (
                  <button
                    key={tab}
                    className={`min-w-[140px] flex-1 border-r border-slate-200 px-6 py-5 text-sm font-medium transition-colors ${
                      index === 0
                        ? "bg-[#cfe2ff] text-white"
                        : "bg-white/90 text-slate-400 hover:bg-slate-50"
                    }`}
                  >
                    {tab}
                  </button>
                ),
              )}
              <button
                onClick={() => setShowLoginModal(true)}
                className="min-w-[140px] border border-red-200 bg-white/90 px-6 py-5 text-sm font-medium text-slate-400 hover:bg-red-50"
              >
                LOGIN
              </button>
            </div>

            <div className="p-4">
              <div className="flex flex-col gap-4 xl:flex-row">
                <div className="flex-1">
                  <div className="relative overflow-hidden rounded-xl bg-[#edf6fb] min-h-[640px] border border-slate-100">
                    <div className="absolute inset-0 bg-white/52 backdrop-blur-[1px]" />
                    <div className="absolute inset-0 opacity-20">
                      <div className="grid grid-cols-12 gap-3 h-full p-6">
                        {Array.from({ length: 120 }).map((_, index) => (
                          <div
                            key={index}
                            className="rounded border border-sky-200/60"
                          />
                        ))}
                      </div>
                    </div>

                    <div className="relative z-10 flex h-full items-center justify-center px-8 py-12">
                      <div className="relative w-full max-w-[1100px]">
                        <div className="flex items-center justify-between gap-4">
                          <div className="absolute left-0 top-20 hidden xl:block">
                            <div className="rounded-full border-8 border-sky-100 bg-white/75 p-5 shadow-lg">
                              <div className="text-6xl opacity-70">🧾</div>
                            </div>
                          </div>

                          <div className="absolute right-20 top-0 hidden xl:block">
                            <div className="rounded-full border-8 border-sky-100 bg-white/75 p-5 shadow-lg">
                              <div className="text-5xl opacity-70">🖥️</div>
                            </div>
                          </div>
                        </div>

                        <div className="mx-auto flex w-full max-w-[720px] items-center justify-center">
                          <div className="relative flex h-[320px] w-[320px] items-center justify-center rounded-full bg-[#33a8dd]/95 shadow-[0_30px_90px_rgba(37,99,235,0.2)]">
                            <div className="flex h-[150px] w-[190px] items-center justify-center rounded-[18px] bg-[#23292f]/95 shadow-inner">
                              <div className="rounded-xl bg-white px-8 py-6 text-[34px] font-light text-slate-700 shadow-sm opacity-95">
                                E-Invoice
                              </div>
                            </div>
                            <div className="absolute -bottom-8 h-6 w-56 rounded-full bg-slate-700" />
                            <div className="absolute -bottom-16 left-1/2 flex -translate-x-1/2 gap-4">
                              <div className="h-10 w-10 rounded-full bg-[#ffe0b3]" />
                              <div className="h-10 w-10 rounded-full bg-[#ffe0b3]" />
                            </div>
                            <button
                              onClick={() => setShowLoginModal(true)}
                              className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-xl bg-[#1244b8] px-10 py-5 text-3xl font-bold tracking-wide text-white shadow-lg hover:bg-[#0f3a9a]"
                            >
                              START EXPERIMENT
                            </button>
                          </div>
                        </div>

                        <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_300px]">
                          <div className="flex flex-wrap gap-6">
                            <div className="flex h-24 w-24 items-center justify-center rounded-full border-8 border-sky-100 bg-white/80 shadow-md">
                              <div className="text-4xl opacity-70">📄</div>
                            </div>
                            <div className="flex h-28 w-[220px] flex-col justify-center rounded-xl border border-slate-200 bg-white/85 p-4 shadow-sm">
                              <div className="text-lg font-semibold text-slate-800 opacity-75">
                                INVOICE
                              </div>
                              <div className="text-sm text-slate-500 opacity-70">
                                Sample document
                              </div>
                            </div>
                            <div className="flex h-28 w-[180px] flex-col justify-center rounded-xl border border-slate-200 bg-white/85 p-4 shadow-sm">
                              <div className="text-sm font-semibold text-slate-800 opacity-75">
                                CREDIT NOTE
                              </div>
                              <div className="text-sm text-slate-500 opacity-70">
                                Document
                              </div>
                            </div>
                            <div className="flex h-28 w-[180px] flex-col justify-center rounded-xl border border-slate-200 bg-white/85 p-4 shadow-sm">
                              <div className="text-sm font-semibold text-slate-800 opacity-75">
                                DEBIT NOTE
                              </div>
                              <div className="text-sm text-slate-500 opacity-70">
                                Document
                              </div>
                            </div>
                          </div>
                          <div className="flex items-center gap-4">
                            <div className="rounded-full bg-amber-400 p-3 shadow-md">
                              <FaPlay className="text-amber-900" />
                            </div>
                            <div className="flex-1 rounded-xl border border-slate-200 bg-white/85 p-4 shadow-sm">
                              <div className="text-sm font-semibold text-slate-800 opacity-75">
                                Invoice
                              </div>
                              <div className="text-xs text-slate-500 opacity-70">
                                Portal module
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="mt-4 rounded-b-xl bg-white/90 px-6 py-4 text-[17px] leading-7 text-blue-700">
                    The e-Invoice System is for GST registered person for
                    uploading all the B2B invoices to the Invoice Registration
                    Portal (IRP). The IRP generates and returns a unique
                    Invoice Reference Number (IRN), digitally signed e-invoice
                    and QR code to the user.
                  </div>
                </div>

                <div className="w-full xl:w-[360px]">
                  <div className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm">
                    <h3 className="text-2xl font-extrabold text-slate-500">
                      LATEST UPDATES
                    </h3>
                    <div className="mt-5 space-y-6">
                      {latestUpdates.map((item) => (
                        <div
                          key={`${item.date}-${item.text}`}
                          className={`border-l-4 pl-4 ${
                            item.color === "blue"
                              ? "border-blue-500"
                              : item.color === "green"
                              ? "border-green-500"
                              : item.color === "orange"
                              ? "border-orange-500"
                              : "border-red-500"
                          }`}
                        >
                          <div className="mb-1 text-sm font-semibold text-slate-400">
                            {item.date}
                          </div>
                          <p className="text-base font-semibold leading-6 text-blue-700/90">
                            • {item.text}
                          </p>
                        </div>
                      ))}
                    </div>
                    <div className="mt-6 text-right text-lg font-semibold text-blue-600">
                      Previous Updates
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-4 rounded-xl bg-[#245f87] px-6 py-5 text-white">
              <div className="text-lg font-semibold uppercase tracking-wide opacity-90">
                  Important Links
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {showLoginModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/20 backdrop-blur-sm px-4">
          <div className="relative w-full max-w-[520px] rounded-2xl bg-[#dfe7f3] p-6 shadow-[0_30px_100px_rgba(15,23,42,0.28)]">
            <button
              onClick={() => setShowLoginModal(false)}
              className="absolute left-4 top-4 text-3xl font-bold text-[#274d80]"
            >
              ×
            </button>

            <div className="flex flex-col items-center gap-3 pt-6">
              <div className="text-6xl">🇮🇳</div>
              <div className="text-2xl font-extrabold text-red-600">
                E-INVOICE SYSTEM LOGIN
              </div>
            </div>

            <div className="mt-5 rounded-md border border-slate-300 bg-slate-100 px-4 py-3 text-sm text-slate-700 shadow-inner">
              <div className="font-semibold text-slate-800">Login Details</div>
              <div className="mt-1">User name: AIR</div>
              <div>Password: Fin@123</div>
            </div>

            <div className="mt-6 space-y-4">
              <div>
                <label className="mb-1 block text-lg text-slate-700">
                  User name
                </label>
                <input
                  value={loginData.username}
                  onChange={(e) =>
                    setLoginData((prev) => ({ ...prev, username: e.target.value }))
                  }
                  className="w-full rounded-md border border-slate-300 bg-white px-4 py-3 text-base shadow-inner outline-none focus:border-blue-500"
                />
              </div>

              <div>
                <label className="mb-1 block text-lg text-slate-700">
                  Password
                </label>
                <input
                  type="password"
                  value={loginData.password}
                  onChange={(e) =>
                    setLoginData((prev) => ({ ...prev, password: e.target.value }))
                  }
                  className="w-full rounded-md border border-slate-300 bg-white px-4 py-3 text-base shadow-inner outline-none focus:border-blue-500"
                />
              </div>

              <div>
                <div className="mb-1 text-lg text-slate-700">
                  Enter Above Captcha
                </div>
                <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                  <div className="flex h-14 items-center justify-center rounded-md border border-slate-300 bg-white px-4 font-mono text-3xl font-black tracking-tight">
                    P2B7(Y
                  </div>
                  <input
                    value={loginData.captcha}
                    onChange={(e) =>
                      setLoginData((prev) => ({ ...prev, captcha: e.target.value }))
                    }
                    className="rounded-md border border-slate-300 bg-white px-4 py-3 text-base shadow-inner outline-none focus:border-blue-500"
                    placeholder="Enter captcha"
                  />
                </div>
              </div>

              <button
                onClick={() => {
                  setShowLoginModal(false);
                  setScreen("dashboard");
                }}
                className="w-full rounded-md border-2 border-red-500 bg-[#0d63d7] py-3 text-2xl font-semibold text-white transition-colors hover:bg-[#0a54ba]"
              >
                LOGIN
              </button>

              <div className="flex items-center justify-between pt-2 text-base text-blue-700">
                <span>Forgot Password ?</span>
                <span>Forgot Username ?</span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );

  const renderDashboard = () => (
    <div className="min-h-screen bg-[#f4f7fb]">
      <div className="bg-[#ec1e18] px-4 py-4 text-center text-3xl font-medium text-white">
        This is a Simulation. Use For Educational Purposes ONLY.
      </div>

      <div className="bg-[#1c6792] px-6 py-6 text-white shadow-sm">
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="text-4xl">🇮🇳</div>
            <div>
              <div className="text-2xl font-bold uppercase leading-tight">
                Goods and Services Tax
              </div>
              <div className="text-2xl font-bold uppercase leading-tight">
                e - INVOICE SYSTEM
              </div>
            </div>
          </div>
          <div className="text-center">
            <div className="text-3xl font-bold">e-Invoice 1 Portal</div>
          </div>
          <div className="flex items-center gap-6">
            <div className="text-right">
              <div className="text-sm font-semibold">NATION TAX MARKET</div>
              <div className="text-xs opacity-80">GST</div>
            </div>
            <div className="text-right">
              <div className="text-sm font-semibold">एनआईसी NIC</div>
              <div className="text-xs opacity-80">
                National Informatics Centre
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="flex min-h-[calc(100vh-152px)]">
        <aside className="w-20 bg-[#d7e0ef] px-2 py-4">
          <div className="mb-5 flex h-10 items-center justify-center text-blue-600">
            <FaHome className="text-lg" />
          </div>
          <div className="flex flex-col gap-5">
            <button className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-white text-slate-500 shadow-sm">
              <FaBars />
            </button>
            <button className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-white text-red-500 shadow-sm">
              <FaVideo />
            </button>
            <button className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-white text-amber-600 shadow-sm">
              <FaCube />
            </button>
            <button className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-white text-orange-500 shadow-sm">
              <FaCog />
            </button>
          </div>
          <div className="mt-10 flex flex-col gap-5">
            <button className="mx-auto text-slate-600">
              <FaInfoCircle />
            </button>
            <button className="mx-auto text-slate-600">
              <FaExclamationTriangle />
            </button>
            <button
              onClick={() => setScreen("home")}
              className="mx-auto text-slate-600"
            >
              <FaArrowLeft />
            </button>
          </div>
        </aside>

        <main className="flex-1 px-6 py-4">
          <div className="mx-auto max-w-[1740px]">
            <div className="bg-[#ccd4e9] px-6 py-3 text-center text-xl text-slate-700">
              <div className="flex items-center justify-between">
                <div className="text-left">
                  GSTIN: 29BRYFP02061V7YP - Name: Company Airlines Pvt. Ltd..
                </div>
                <div>Account : Main User</div>
                <div>Client IP:1.1.1.1</div>
                <button
                  onClick={() => setScreen("home")}
                  className="text-blue-700"
                >
                  <FaPowerOff />
                </button>
              </div>
            </div>

            <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
              <section className="rounded-b-xl bg-white shadow-sm">
                <div className="px-6 pt-4 text-center text-4xl font-extrabold text-[#1b66a0]">
                  Dash Board
                </div>

                <div className="mt-4 grid gap-6 px-6 md:grid-cols-2">
                  <div className="rounded border border-blue-200">
                    <div className="flex items-center justify-between bg-blue-500 px-4 py-3 text-white">
                      <div className="font-semibold">Generations</div>
                      <div>◔</div>
                    </div>
                    <div className="bg-white px-4 py-4 text-lg text-slate-700">
                      <div className="flex justify-between border-b border-slate-200 py-2">
                        <span className="underline">Yesterday</span>
                        <span className="underline">0</span>
                      </div>
                      <div className="flex justify-between py-2">
                        <span className="underline">During This month</span>
                        <span className="underline">67</span>
                      </div>
                    </div>
                  </div>

                  <div className="rounded border border-red-200">
                    <div className="flex items-center justify-between bg-red-500 px-4 py-3 text-white">
                      <div className="font-semibold">Cancelled</div>
                      <div>↪</div>
                    </div>
                    <div className="bg-white px-4 py-4 text-lg text-slate-700">
                      <div className="flex justify-between border-b border-slate-200 py-2">
                        <span className="underline">Yesterday</span>
                        <span className="underline">0</span>
                      </div>
                      <div className="flex justify-between py-2">
                        <span className="underline">During This month</span>
                        <span className="underline">0</span>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="mx-6 mt-6 rounded border border-slate-200 bg-white">
                  <div className="border-b border-slate-200 px-4 py-2 text-2xl font-semibold text-cyan-500">
                    Notes:
                  </div>
                  <div className="space-y-4 px-6 py-5 text-lg text-slate-700">
                    <div className="flex gap-3">
                      <span>•</span>
                      <span>
                        The Bulk IRN generation facility has been enabled. You
                        may download the tools from the portal under Help -&gt;
                        Tools.
                      </span>
                    </div>
                    <div className="flex gap-3">
                      <span>•</span>
                      <span>
                        The e-Waybills generated in this portal will be
                        reflected in the e-waybill system. To Update Part-B
                        details, cancel or extend, you may login to e-waybill
                        system with same credentials.
                      </span>
                    </div>
                  </div>
                </div>

                <div className="flex items-center justify-end gap-4 px-6 py-6">
                  <button
                    onClick={() => setScreen("home")}
                    className="rounded-md border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50"
                  >
                    Back to Portal
                  </button>
                  <button
                    onClick={goToInvoiceBuilder}
                    className="rounded-md bg-blue-700 px-5 py-3 text-sm font-semibold text-white hover:bg-blue-800"
                  >
                    Continue to Invoice Builder
                  </button>
                </div>
              </section>

              <aside className="rounded-xl bg-white p-5 shadow-sm">
                <div className="text-2xl font-extrabold text-slate-500">
                  LATEST UPDATES
                </div>
                <div className="mt-6 space-y-5">
                  {latestUpdates.map((item) => (
                    <div
                      key={`${item.date}-${item.text}-dashboard`}
                      className={`border-l-4 pl-4 ${
                        item.color === "blue"
                          ? "border-blue-500"
                          : item.color === "green"
                          ? "border-green-500"
                          : item.color === "orange"
                          ? "border-orange-500"
                          : "border-red-500"
                      }`}
                    >
                      <div className="text-sm font-semibold text-slate-500">
                        {item.date}
                      </div>
                      <p className="text-base font-semibold leading-6 text-blue-700">
                        • {item.text}
                      </p>
                    </div>
                  ))}
                </div>
                <div className="mt-6 text-right text-lg font-semibold text-blue-600">
                  Previous Updates
                </div>
              </aside>
            </div>

            <div className="mt-4 flex items-center justify-between bg-[#1d5d83] px-4 py-3 text-white">
              <div className="text-lg">Version 1.01</div>
              <div className="text-lg">© 2022 - Powered By National Informatics Centre.</div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );

  const renderInvoiceBuilder = () => (
    <div className="min-h-screen bg-slate-50">
      <div className="border-b border-slate-200 bg-white px-4 py-3 shadow-sm">
        <div className="mx-auto flex max-w-[1800px] items-center justify-between">
          <button
            onClick={() => router.push("/simulations/gst/e-invoicing-1")}
            className="rounded-md border border-slate-300 bg-slate-50 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-100"
          >
            Back to Portal Replica
          </button>
          <div className="text-lg font-semibold text-slate-700">
            GST E-Invoice Builder
          </div>
          <div className="text-sm text-slate-500">
            Route: /simulations/gst/e-invoicing-1/invoice
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-[1800px] p-4">
        <GSTSimulation />
      </div>
    </div>
  );

  if (screen === "invoice") {
    return renderInvoiceBuilder();
  }

  return (
    <div>
      <ClipboardOnlyGuard />
      {screen === "home"
        ? renderHomeScreen()
        : screen === "dashboard"
        ? renderDashboard()
        : renderInvoiceBuilder()}
    </div>
  );
}
